# Railway deployment configuration
# This tells Railway how to build and run your API

[build]
builder = "nixpacks"

[deploy]
startCommand = "node server/secure-chatbot-api.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NODE_ENV = "production"
PORT = { { RAILWAY_PORT } }

# Domain configuration (Railway will provide this)
RAILWAY_STATIC_URL = { { RAILWAY_STATIC_URL } }
ALLOWED_ORIGINS = "https://robert-herzig.github.io,https://pwa-language-learning-api.railway.app"
